### ISSUE TITLE
ImportError: cannot import name 'Sequence' from 'collections' (C:\Program Files\Python3\lib\collections\__init__.py) (venv)

### ISSUE THREAD

**Issue by nnnkkk9** [CiscoDevNet/aci-learning-labs-code-samples#10]
There seems to be this error even on the solution file. The full output is: 
F:\Other\DevNet\aci-learning-labs-code-samples\venv\lib\site-packages\acitoolkit-0.4-py3.10.egg\acitoolkit\acitoolkit.py:5207: SyntaxWarning: "is not" with a literal. Did you mean "!="?
F:\Other\DevNet\aci-learning-labs-code-samples\venv\lib\site-packages\acitoolkit-0.4-py3.10.egg\acitoolkit\acitoolkit.py:5207: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Traceback (most recent call last):
  File "F:\Other\DevNet\aci-learning-labs-code-samples\sbx-intro-aci\sbx-intro-aci-mission_toolkit\aci_critical_faults_SOLUTION.py", line 9, in <module>
    from acitoolkit.acitoolkit import Session
  File "F:\Other\DevNet\aci-learning-labs-code-samples\venv\lib\site-packages\acitoolkit-0.4-py3.10.egg\acitoolkit\__init__.py", line 35, in <module>
  File "F:\Other\DevNet\aci-learning-labs-code-samples\venv\lib\site-packages\acitoolkit-0.4-py3.10.egg\acitoolkit\acitoolkit.py", line 33, in <module>

ImportError: cannot import name 'Sequence' from 'collections' (C:\Program Files\Python3\lib\collections\__init__.py)
(venv)

I ran in the venv created for this lab only. Does anybody have an idea what the issue might be?

**Comment by Prabal1990** [comment]
I am facing the same issue
