### ISSUE TITLE
baseline.py not executable for me

### ISSUE THREAD

**Issue by xanderstevenson** [CiscoDevNet/aci-learning-labs-code-samples#13]
python3 baseline.py

Traceback (most recent call last):
  File "/Users/alexstev/Documents/CiscoDevNet/code/aci-learning-labs-code-samples/apic_fabric_setup/baseline.py", line 11, in <module>
    import startup_script
  File "/Users/alexstev/Documents/CiscoDevNet/code/aci-learning-labs-code-samples/apic_fabric_setup/startup_script.py", line 3, in <module>
    import cobra.mit.access
  File "/Users/alexstev/Documents/CiscoDevNet/code/aci-learning-labs-code-samples/ven/lib/python3.9/site-packages/cobra/__init__.py", line 17, in <module>
    from cobra import io
  File "/Users/alexstev/Documents/CiscoDevNet/code/aci-learning-labs-code-samples/ven/lib/python3.9/site-packages/cobra/io/__init__.py", line 4, in <module>
    from cobra.io.dict import model_from_dict, model_to_dict
  File "/Users/alexstev/Documents/CiscoDevNet/code/aci-learning-labs-code-samples/ven/lib/python3.9/site-packages/cobra/io/dict.py", line 71, in <module>
    value: Union[str, np.float, np.bool, Set, Dict]
  File "/Users/alexstev/Documents/CiscoDevNet/code/aci-learning-labs-code-samples/ven/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

I tried updating numpy but that didn't help

**Comment by caitube900610** [comment]
same for me 
(ACI) ec2-user:~/environment/aci-learning-labs-code-samples/apic_fabric_setup (master) $ python baseline.py 
Traceback (most recent call last):
  File "/home/ec2-user/environment/aci-learning-labs-code-samples/apic_fabric_setup/baseline.py", line 11, in <module>
    import startup_script
  File "/home/ec2-user/environment/aci-learning-labs-code-samples/apic_fabric_setup/startup_script.py", line 3, in <module>
    import cobra.mit.access
ModuleNotFoundError: No module named 'cobra'
