### ISSUE TITLE
Unable to run starup baseline script

### ISSUE THREAD

**Issue by g-arjuna** [CiscoDevNet/aci-learning-labs-code-samples#9]
Traceback (most recent call last):
  File "baseline.py", line 11, in <module>
    import startup_script
  File "C:\Users\arjun\Desktop\dev\aci-learning-labs-code-samples\apic_fabric_setup\startup_script.py", line 225, in <module>
    md.commit(c)
  File "C:\Users\arjun\Desktop\dev\aci-learning-labs-code-samples\venv\lib\site-packages\cobra\mit\access.py", line 66, in commit
    return self._accessImpl.post(configObject)
  File "C:\Users\arjun\Desktop\dev\aci-learning-labs-code-samples\venv\lib\site-packages\cobra\internal\rest\accessimpl.py", line 182, in post
    return self.__parseError(rsp, CommitError, rsp.status_code)
  File "C:\Users\arjun\Desktop\dev\aci-learning-labs-code-samples\venv\lib\site-packages\cobra\internal\rest\accessimpl.py", line 240, in __parseError
    parseXMLError(rsp.text, errorClass, httpCode)
  File "C:\Users\arjun\Desktop\dev\aci-learning-labs-code-samples\venv\lib\site-packages\cobra\mit\xmlcodec.py", line 20, in parseXMLError
    raise errorClass(int(errorCode), errorStr, httpCode)
cobra.mit.request.CommitError: Validation failed: Validation failed for node: 101Overlapping interfaces. Last examined: uni/infra/accportprof-Heroes_server1

**Comment by xanderstevenson** [comment]
This might be similar to this issue, with port blocks overlapping:

https://community.cisco.com/t5/controllers/aci-sdk-baseline-py-error-cobra-mit-request-commiterror/td-p/3905604
